### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#10]
The project should have a development pipeline, ensuring that the tests always pass on each commit.
Here are some CI providers:
* **[TravisCI](https://travis-ci.org/)**
* [CircleCI](https://circleci.com/)
* [AppVeyor](https://www.appveyor.com/)

### Nessessary steps
- [x] Add clio to TravisCI
- [x] Add .travis.yml
- [x] Add Travis build status badge to readme

### Possible configurations
- [x] run all tests on every commit
- [x] test builds against multiple node versions (8, 9 and 10)

**Comment by pouya-eghbali** [comment]
I've investigated this before, but I haven't checked AppVeyor. I have Clio on TravisCI, with no builds, I was just investigating what's the best tool. What's your experience?

**Comment by garritfra** [comment]
TravisCI is really simple to use and it is free. CircleCI has faster builds, but only by a fraction. Do you want to integrate Travis?

**Comment by pouya-eghbali** [comment]
Yeah it seems like a decent choice. What are the required steps?

**Comment by garritfra** [comment]
I'll add a checklist to the description. I'd say we make an extra branch for that, in case we need to spam test-commits😂

**Comment by pouya-eghbali** [comment]
Ok, done. I guess XD

**Comment by garritfra** [comment]
Can this be closed?

**Comment by garritfra** [comment]
Just checking the build log. I noticed that the tests don't seem to run🧐 Can you investigate that? Maybe it has something to do with the cache?
```
$ npm test
> clio-lang@0.1.3 test /home/travis/build/clio-lang/clio
> jest --collect-coverage
The command "npm test" exited with 0.
store build cache
nothing changed, not updating cache
Done. Your build exited with 0.
```
