### ISSUE TITLE
Replace Degit with internal npm package

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#109]
We currently use Degit when generating a new clio project. The template repositories (https://github.com/clio-lang/template-node and https://github.com/clio-lang/template-web) should however live in a package inside the main repo, to avoid inconsistency errors

Related: #137

**Comment by pouya-eghbali** [comment]
Closing this. Degit is fine, specially with the new --template flag, they go really well together. There are no more "node" or "browser" targets, we just have one "js" target, templates are now responsible for "start" and "host" commands, minimizes the inconsistency errors.
