### ISSUE TITLE
Replace yargs

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#12]
Main reason is bundle size
Some options:
* Self written parser
* Commander

**Comment by pouya-eghbali** [comment]
Commander seems like a proper choice as it's 1/7 the size of yargs, but still ~30kb. Pretty sure it'll not affect performance as much as yargs does. Clio start time is slow now probably because yargs (and other various modules we import)

**Comment by pouya-eghbali** [comment]
Closing this, it's not a priority now, we should see how the new Clio is going to work with yargs, then we can decide.
