### ISSUE TITLE
Compilation Error Reporting

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#128]
`v0.1.x` featured very good compile error reporting. In the upcoming `v0.2.0` release, we will need to match this.

We still have the `clioException.js` file from `v0.1`, that we can probably recycle. It should give hints about syntax errors and their positions in the source file.

**Comment by pouya-eghbali** [comment]
I think the v0.2.0-alpha.0 is already doing a good job here, however it can be improved:

```clio
export fn main argv:
  [39 40 41 + 42]
```

And the error:

```
Error: main.clio:

1 | export fn main argv:
2 |   [39 40 41 + 42]
                ^
Expecting one of Range, Array, Wrapped, Number, String or Symbol at 2:12 but encountered Add
```

**Comment by pouya-eghbali** [comment]
Closing this, compilation errors are much much better now, not perfect but it's improving on each release.
