### ISSUE TITLE
Maintainance Fixes🧹

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#134]
We should tidy up some bits of our code:

### Path Joins

- [ ] `path.join` should not contain multiple path components in an argument. 

We should replace these joins:

```
path.join(dir.name, "build/node", "package.json")
```

with:

```
path.join(dir.name, "build", "node", "package.json")
```
_Originally posted by @pouya-eghbali in https://github.com/clio-lang/clio/pull/129#discussion_r368257375_

### Deep equal checks

- [ ]  equal (`==`) checks should be replaced by deep euqal (`===`) checks in most cases.

_Originally posted by @garritfra in https://github.com/clio-lang/clio/pull/132#discussion_r368714652_

**Comment by djKooks** [comment]
You mean it should work same as functions in `node`?

**Comment by garritfra** [comment]
@djKooks this issues scope is to clean up some hiccups in the compilers source code, not the language itself
