### ISSUE TITLE
clio new --template flag?

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#137]
I want to propose a way to use custom templates for project generation. We currently provide our own templates, but it would be nice to let the users make own templates. 

Related: #109

**Comment by pouya-eghbali** [comment]
I'm removing the parcel dependency. I'm going to add a few entries to the generated package.json. First of all we'll change our official web template to have parcel as dev dependency. The second change is to add `start`, `host`, `serve` and `bundle` entries so people can do `npm run start` or etc. I will add the template flag next so people can make custom templates with their favorite bundlers.

**Comment by pouya-eghbali** [comment]
This is now on 0.8 branch
