### ISSUE TITLE
Build command should overwrite build directory

### ISSUE THREAD

**Issue by pouya-eghbali** [clio-lang/clio#158]
**Describe the bug**

This ensures clean builds and fixes some possible unexpected behaviors. Built files can be cached in a .cache directory if rebuilding files every time is a concern. 

An example of unexpected behavior: Try building your project, adding a new npm dependency to config.toml, and rebuilding. You'll see that the new npm dependency does not get added to the generated package.json.

**To Reproduce**
1. Run `clio new xyz && cd xyz`
2. Run `clio build`
3. Run  `echo "[npm_dependencies]\nexpress = \"^4.17.1\"'\n" >> clio.toml`
4. Run `clio build` again
2. See error

**Expected behavior**
express should be added to the generated package.json

**Versions (please complete the following information):**
 - OS: FreeBSD 12.1
 - Clio: develop
 - Node: 13.3.0
 - NPM: 6.13.0
 
**Possible solutions**
 - Remove and recreate build dir on every build
 - Overwrite package.json as an alternative solution

**Additional context**
First possible solution combined with a caching mechanism for node_modules and generated files is the best option imo, it prevents unexpected behavior in future.

**Comment by garritfra** [comment]
I'll grab this on the weekend
