### ISSUE TITLE
Bash does not display anything after clio init

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#16]
after running `clio init`, bash wont display any input.
Testet on MacOS

### Steps to reproduce
1. make a new directory
2. run clio init
3. wait for stdlib to download
4. type input

**Comment by pouya-eghbali** [comment]
Works as expected on Arch, zsh. I confirm there's a problem with bash. I suspect we print `\r` without printing `\n` in the end.

**Comment by garritfra** [comment]
I've never actually seen this bug in the wild before, just on paper I'd think that \n always returns the cursor to the beginning of the line

**Comment by garritfra** [comment]
Closed with the recent refactoring in #38
