### ISSUE TITLE
New lexer / parser / code generator

### ISSUE THREAD

**Issue by pouya-eghbali** [clio-lang/clio#17]
We're currently using a hand built lexer, parser and code generator for Clio. These aren't feature rich and are causing us a few issues (lexing/parsing errors not being clear for example). Instead of extending the lexer / parser I decided to use a library for doing this.

I chose `chevrotain`, it has really good support, documentation and API. This will also make it easier for contributors who wish to add features to the language.

**Comment by pouya-eghbali** [comment]
I made a new branch and pushed the new parser, it's not complete yet, working on it. Hope it makes it easier to develop Clio.

**Comment by pouya-eghbali** [comment]
`chevrotain` plan didn't really work well, instead I wrote my own parsing engine. The new parser engine has a very small core (~20 lines) and it's easy to understand. The error reporting is improved, and it has a lot of advantages over `chevrotain`.

I also changed the AST format and how we generate JS code. Soon this will be in core.

**Comment by raphaelkieling** [comment]
Where did you read about parsers and compilers? Clio is a nice language, congrats

**Comment by pouya-eghbali** [comment]
Thank you @raphaelkieling , I'm interested in programming languages and text mining / natural language processing, I made a lot of toy languages and experimented with nlp a lot, I don't remember any specific articles / papers about parsers and compilers. Anyways, here's the link to our new parser engine: 

https://github.com/pouya-eghbali/bean

This is going to replace a huge part of Clio, I'm not really satisfied with the current parser, I just wanted to make the language _quickly_ and did a lot of dirty hacks with the current parser, I'm replacing it with a proper one.

Sadly I work 100% and I cannot spend a lot of time on this, but I'm doing my best, we're looking to hire some developers [in Iran, for various reasons] to help me with some Clio stuff.

**Comment by raphaelkieling** [comment]
wow, perfect! I will go study your bean parser engine. but not give up clio, it's a good ideia, if need i will go help u

**Comment by garritfra** [comment]
@raphaelkieling also feel free to join our telegram group! :) Link is in the readme

**Comment by pouya-eghbali** [comment]
Closing this for #24
