### ISSUE TITLE
Arrays are not mappable

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#171]
**Describe the bug**
When going through the examples in the documentation, I noticed that arrays are not mappable. The following error is thrown instead:
```
Error: Cannot read property '0' of undefined
```

**To Reproduce**

1. Create a new Project
2. Add the following snippet to `src/main.clio`:
```
fn double n:
  n * 2

[0 1 2] -> * double -> * print
```

**Expected behavior**
This is printed to stdout:
```
0
1
2
```

**Versions (please complete the following information):**

- OS: MacOS Catalina
- Clio: develop
- Node: v12.13.1
- NPM: 6.13.7

**Possible solutions**

- Use range lazy evaluation for arrays?

**Comment by pouya-eghbali** [comment]
I see a very different behavior:

![image](https://user-images.githubusercontent.com/4604055/74375461-a5ece400-4de0-11ea-8e7a-48cab79c66f7.png)

It gets printed twice.

**Comment by pouya-eghbali** [comment]
Ok, this is weird. I get the error now, in a new project. I had some cached stuff somewhere.

**Comment by garritfra** [comment]
That's weird. We should keep an eye on the result of your first run
