### ISSUE TITLE
Please mirror Medium articles or just publish elsewhere

### ISSUE THREAD

**Issue by fuzzthink** [clio-lang/clio#19]
Medium is not open.

"You’ve reached the end of your free member preview for this month. Become a member now for $5/month to read this story and get unlimited access to all of the best stories on Medium."

The wiki here may be a good alternative.

**Comment by pouya-eghbali** [comment]
Hello. The only reason we made the articles paid was to get Medium to recommend them to people who are interested, this is apparently only available for paid articles and we got a lot of views just by making the articles paid.

I agree with mirroring them in the wiki, or I can share the `friend link` to give free access to the articles.

**Comment by pouya-eghbali** [comment]
I added friend links here: https://docs.clio-lang.org/medium-articles
I will add links to new articles as I publish them.
