### ISSUE TITLE
Logo on the playground overlays part of the code editor in Firefox.

### ISSUE THREAD

**Issue by its-danny** [clio-lang/clio#196]
## Describe whats wrong or missing

Firefox [doesn't support](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) the `zoom` CSS property, causing the Clio logo to hide the first line of code in the playground.

![Capture](https://user-images.githubusercontent.com/60604/111653266-04934700-87c5-11eb-9862-0af1d92cd3c0.PNG)

## ToDo

Either use [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale()) or just set the width.

---

P.S. Great work on the language, probably the slickest syntax I've seen.

**Comment by pouya-eghbali** [comment]
Fixed with #200 
I set it to a fixed size, thanks for reporting!
