### ISSUE TITLE
Add preview of compiled JS code for code snippets 

### ISSUE THREAD

**Issue by BennyAlex** [clio-lang/clio#198]
Hello,

to better understand how clio works and what it does, it would be nice to have a tab/side-by-side view for the transpiled JS code.
Something like codepen does with scss/less/etc...

Thanks in advance :D

**Comment by garritfra** [comment]
Hi, thanks for your request. I'm afraid that this is a very broad topic that cannot just be implemented into the language. What you could do is to compile a file and then look at the output. It should be more or less readable. A side-by-side view would require a plugin for your code editor, but you could go ahead and do that manually.

**Comment by BennyAlex** [comment]
I meant to do it in the documentation. For not-editable code, you could simply compile it (like when building/deploying the site) and also display it on the documentation website
