### ISSUE TITLE
Error: Cannot find module 'clio-utils' after installation.

### ISSUE THREAD

**Issue by chekaninmaxim** [clio-lang/clio#199]
ubuntu 20.04
npm v6.14.8 node v14.7.0

I tried both ways to install the clio that provided in documentation
https://docs.clio-lang.org/install
But I'm getting this error:
`Error: Cannot find module 'clio-utils'
`

**Comment by HussainArif12** [comment]
Getting the same error.

**Comment by alex-gunning-jumo** [comment]
Same

**Comment by pouya-eghbali** [comment]
Ok, I see what's the issue. We have:

```
"bin": {
    "clio": "packages/cli/index.js"
  },
```

On our toplevel package, however the dependencies of the "packages/cli" aren't getting installed (not listed on toplevel package). I'm trying to find out the best way of dealing with this.

**Comment by pouya-eghbali** [comment]
Issue fixed in https://github.com/clio-lang/clio/commit/04a9b6808f47c0229bb3d908aa60be0facabbcaf
