### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by micheleriva** [clio-lang/clio#2]
Hi!
I have read your Medium article about Clio Lang and I really loved it.
I'd love to contribute to the project, is there a contribution guide to follow?

Thank you!

**Comment by pouya-eghbali** [comment]
Hi Michele, thanks for your interest in Clio!

We don't have a contribution guide yet, but I will start working on it now and I guess I'll be able to get it ready by tomorrow.
In the meantime, feel free to join our community on Telegram so we can discuss your ideas.

https://t.me/joinchat/B0kZo0kVldfXldTDqz95XA

**Comment by rusfearuth** [comment]
Hey!

I have read your article at Medium too. I like Clio too! How can I help to your project?

**Comment by pouya-eghbali** [comment]
I just published our first contribution guide draft, let me know if you have any suggestions or if it doesn't cover some important topics.
