### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by fuzzthink** [clio-lang/clio#20]
First example:
```
fn fib n:
  if n < 2:  n
      else: (n - 1 -> fib) +
            (n - 2 -> fib)

[0:10] -> * fib -> print
```

```
$ clio run eg.clio 

 At file "eg.clio" when calling print:

   4 │             (n - 2 -> fib)
   5 │ 
   6 │ [0:10] -> * fib -> print
                          ^ At line 6 char 19

 Exception: BigInt is not defined
```

Installed as in instruction:
`npm i -g clio-lang`

**Comment by garritfra** [comment]
Thanks for this issue!
What version of clio are you using? As far as I'm concerned, `BigInt` was used as a wrapper in older versions of clio, but it has been replaced as of `0.1.0`

**Comment by raphaelkieling** [comment]
I my case, that work:

```
fn fib n:
  if n < 2:  n
      else: (n - 1 -> fib) + (n - 2 -> fib)

10 -> fib -> print

//output: 55
```

but if i use `[0:10] -> * fib -> print` output is `[object Object]`. this is correct?

**Comment by fuzzthink** [comment]
Clio version: 0.1.5

output is 55 if
`10 -> fib -> print`

output is exception as stated if `[0:10] -> * fib -> print`

**Comment by fuzzthink** [comment]
Ah, issue was node was v8.15.0. Works with node v10.14.

But why output is `[object Object]` when output in online editor prints the array?

**Comment by raphaelkieling** [comment]
i don't know... my node version is `v11.11.0`

**Comment by raphaelkieling** [comment]
> Works with node v10.14

Hmm, interesting, i not did tests in old version

**Comment by fuzzthink** [comment]
Any thoughts on why difference in output in online editor vs. local run?

**Comment by raphaelkieling** [comment]
i 've no ideia, on my terminal a array output `[1,2,3,4,5,6]` normally, but this especific function `[0:10] -> * fib -> print` print a object. What your terminal print?

**Comment by pouya-eghbali** [comment]
Ranges are lazy in Clio, here's why it prints `[object Object]` (it shouldn't, i'll fix it soon):

1. `[0:10]` compiles to

```
LazyRange({
    start: 0,
    end: 10,
    step: 1,
    get: (i, self) => self.start + self.step * i
})
```

2. When you map `fib` to this `LazyRange` object it becomes:

LazyRange({
    start: 0,
    end: 10,
    step: 1,
    get: (i, self) => fib(self.start + self.step * i)
})
```

3. When you call print on this object, it outputs `[object Object]` because it is an object. However if you map print to it, it will print the contents correctly. Anyways this isn't the correct behavior and should be fixed, I'll look into it, as I said I'm a little busy with the new parser and when I finish I will have more time to fix these issues.

I'm afraid most of these will need rewriting so I prefer if I don't touch the current built-ins / definitions. Also, thanks for testing Clio and reporting the bugs, makes me happy to see people are interested, hopefully we'll be able to use Clio in production soon, I have lots of plans for this language.

**Comment by garritfra** [comment]
@pouya-eghbali should we open a new ticket for this, and close this one?

**Comment by pouya-eghbali** [comment]
Yes, I'll make another issue stating all the new changes and what's blocking us rn, all decisions and etc, I guess it's good to share these with the community.

**Comment by pouya-eghbali** [comment]
Closing this for #24 
We're making a lot of changes, these are breaking changes and this issues will not be relevant anymore.
