### ISSUE TITLE
clio run failure in windows 10 [Version 10.0.21387.1]

### ISSUE THREAD

**Issue by hsmyers** [clio-lang/clio#207]
Here is a screen capture:
`c:\Users\hsmyers\clio>clio new hello
Info: Added Clio dependencies
Info: Initialized new git repository.
Info: Initialization Complete!
Success: Run 'cd hello' to open, then 'clio run' to run the project!

c:\Users\hsmyers\clio>cd hello

c:\Users\hsmyers\clio\hello>clio run
Info: Creating build for node
× Error: Error: EINVAL: invalid argument, mkdir 'c:\c:'
Compilation Error: EINVAL: invalid argument, mkdir 'c:\c:'`

**Expected behavior**
I expected it to work.

**Screenshots**

**Versions (please complete the following information):**

- Windows Version 10.0.21387.1
- Clio: 0.5.1
- Node: v14.17.0
- NPM: 6.14.13

**Possible solutions**
??!! Suggest you look at getting a windows box and actually using it.

**Comment by Ivo-Balbaert** [comment]
I have the same error for clio v 0.6.0
When the new project is on a different drive, for example d: , the error is:
× Error: Error: EINVAL: invalid argument, mkdir 'D:\D:'
Compilation Error: EINVAL: invalid argument, mkdir 'D:\D:'

**Comment by hsmyers** [comment]
So would someone provide a link to the likely source of this obvious typo?

**Comment by Ivo-Balbaert** [comment]
I have installed and run successfully a new Clio v 0.6 project on Ubtuntu 20 and WSL2 in Windows. 
But my main dev-box is Windows 10, so I can quickly test out any change/correction or new versions.

**Comment by hsmyers** [comment]
Same here, although I run a bleeding-edge version of both windows and wsl
(wsld in my case.)

**Comment by pouya-eghbali** [comment]
I'll be working on a fix tonight, I will investigate the issue. Unfortunately I do not have a windows computer to test, but I guess I can just get a VM for a few hours.

**Comment by Ivo-Balbaert** [comment]
I have located the error: it occurs when executing the line 182
   **mkdir(destDir);**
 in the script build.js

In my case I'm working in folder D:\Clio\own_projects\hello - the value of variable destDir is the string  D:\Clio\own_projects\hello\build\node ; the error is: × Error: Error: EINVAL: invalid argument, mkdir 'D:\D:'
Compilation Error: EINVAL: invalid argument, mkdir 'D:\D:'

**Comment by hsmyers** [comment]
@ibalbaert Excellent work! Is your setup sufficient to do a build?

**Comment by Ivo-Balbaert** [comment]
Should be possible to build, but as yet don't  know how to fix the error.

**Comment by hsmyers** [comment]
Let me take a look at build.js…

**Comment by hsmyers** [comment]
Post a note when the change is available for a new install?

**Comment by Ivo-Balbaert** [comment]
I just tested with the new Clio from a few minutes ago: it works!


D:\Clio\own_projects\hello>clio run
Info: Creating build for node
√ Compiling source...
√ Adding Clio start script...
√ Installing npm dependencies (this may take a while)...
Hello World

**Comment by hsmyers** [comment]
Same here! Great work Pouya!!
