### ISSUE TITLE
The comment syntax -- is rejected everywhere in code

### ISSUE THREAD

**Issue by Ivo-Balbaert** [clio-lang/clio#217]
**Describe the bug**

To Reproduce
In the following program the first comment line is rejected:

```
-- A a program that prints out a number
export fn main argv:
  5 -> console.log 
```

We get during compilation (clio run) the following error:
D:\Clio\tests_for_issues\test_comments2>clio run
Info: Compiling from "clio.toml"
Info: Creating build for target "js"
- Compiling source...Parsing error at main.clio[1:1]

-- A program that prints out a number
 ^

Expecting one of  but encountered subOp

Expected behavior
All comments should be ignored, and the output should be:
5

Versions
    • OS: Windows 10
    • Clio: 0.8.1
    • Node: v14.16.1
    • NPM: 6.14.12

**Additional context**

The -- syntax is rejected everywhere in code like this:

```
-- A a program that prints out a number
export fn main argv:
-- B inside the function before other code
  5 -> console.log -- C on the actual printing line
  "Hello" -> console.log
-- E after the code
```
The error is always like the following:

Expecting one of lineBreak, symbol, parameter, number, array, string, formattedString, hashmap, propertyAccess, range, rangeFull, rangeBy, byRange, ranger, slice, set, wrapped, awaited, parallelFn, null, true, false, inCheck, group but encountered subOp

**This is a regression, it was not a problem in Clio: 0.7.0**

It is strange: it only happens when building a new project in 0.8.1 with comments,
an older project with comments is not affected (provided it's clio.toml is changed to the 0.8.1 version).

**Comment by pouya-eghbali** [comment]
This is strange, I ran both examples both on the playground and also on my laptop using Clio 0.8.1 (on Node 16.4.2), both examples run without any issue!

**Comment by Ivo-Balbaert** [comment]
Ok, I found the cause of this error, it is a Windows issue: I edited the code and added comments in VS Code with CRLF as End of Line Sequence.
When I changed this in the status bar to LF, the errors dissappear.
Perhaps you can add this as an info to: https://docs.clio-lang.org/versions/develop/tools/vscode.html

**Comment by pouya-eghbali** [comment]
> Ok, I found the cause of this error, it is a Windows issue: I edited the code and added comments in VS Code with CRLF as End of Line Sequence.
> When I changed this in the status bar to LF, the errors dissappear.
> Perhaps you can add this as an info to: https://docs.clio-lang.org/versions/develop/tools/vscode.html

That is strange, ~~our lexer IGNORES all CR characters, so it should just work.~~ Ok just checked, the lexer does actually ignore all CR characters, but it doesn't do that in comments. I'll reopen this issue and fix it in the next release.
