### ISSUE TITLE
In the current documentation the branching section is still present:

### ISSUE THREAD

**Issue by Ivo-Balbaert** [clio-lang/clio#218]
In the current documentation the branching section is still present:

[branching](https://docs.clio-lang.org/learn/official-tutorial/flows#branching)

_Originally posted by @Ivo-Balbaert in https://github.com/clio-lang/clio/issues/213#issuecomment-873548389_

**Comment by pouya-eghbali** [comment]
Removed in the new documentation, thanks for reporting!
