### ISSUE TITLE
Errors and Questions

### ISSUE THREAD

**Issue by fuzzthink** [clio-lang/clio#22]
Questions
1. Why
`'2' -> Number -> print`
raised exception?
```
   1 │ '2' -> Number -> print
              ^ At line 1 char 7
 Exception: Cannot read property 'call' of undefined
```
But online editor outputs 2?

2. In online editor,
`'2' -> Number -> typeof -> print`

outputs `function Number() { [native code] }`
It should output "string"

Thinking it's returning `typeof Number`, I edit it to:
`('2' -> Number) -> typeof -> print`
and it outputs the same `function Number() { [native code] }`, why?

3. Say if I want to use parseInt(n, base) instead.
Run of `'2' -> parseInt -> typeof -> print` gives:
```
   1 │ '2' -> parseInt -> typeof -> print
              ^ At line 1 char 7
 Exception: Cannot read property 'call' of undefined
```

4. Say if it doesn't error, is this how I pass the 2nd argument base to parseInt?
Run of `'2' -> parseInt 10 -> typeof -> print`

**Comment by fuzzthink** [comment]
Same Exception errors for 1) and 3) after installing and using the following versions of node:

node v10.15.3 (npm v6.4.1)  -- LTS
node v11.11.0 (npm v6.7.0)

**Comment by pouya-eghbali** [comment]
Online editor doesn't have the most recent Clio version so the behavior is different. We also don't call JavaScript functions directly and that's causing a lot of issues (Well, Clio is supposed to be lazy and pure and this requires a lot of run-time manipulations, with the new parser and the new code generator I'm taking a different approach to laziness / pure functional programming and that will solve all of these issues)

**Comment by pouya-eghbali** [comment]
Closing this for #24 
Once #24 is done i'll update the online editor with new code.
