### ISSUE TITLE
Installation instructions should indicate min Node.js version

### ISSUE THREAD

**Issue by chuckwondo** [clio-lang/clio#221]
## Describe whats wrong or missing\*\*

The installation instructions (https://docs.clio-lang.org/install) should indicate that Node.js v15.x is the minimum required version, otherwise running `clio new tutorial` fails with the following error:

```plain
Error: fs.rmSync is not a function
```

**Comment by Ivo-Balbaert** [comment]
On Windows 10 I am running node -v v14.16.1,
but clio new works for me.

**Comment by chuckwondo** [comment]
I was using v14.5.0 when I got the error. As it turns out, `fs.rmSync` wasn't added until v14.14.0, so that should be documented as the minimum required version.

**Comment by Ivo-Balbaert** [comment]
Thanks for specifying that!
