### ISSUE TITLE
importing npm modules not working.

### ISSUE THREAD

**Issue by z0ppi-old** [clio-lang/clio#228]
**Describe the bug**
So im trying to use express but its saying it cant find it

**To Reproduce**
here:

1. create a new project
2. run `clio deps add --npm express`
3. in src/main.clio put `import "express"`

**Expected behavior**
import it.

**Screenshots**
![image](https://user-images.githubusercontent.com/89263674/133897965-726e87a7-5e6b-45e5-b907-9631887123ea.png)
![image](https://user-images.githubusercontent.com/89263674/133897970-58a63b75-d8eb-466a-866c-19f8df35c2b9.png)

**Versions (please complete the following information):**

- OS: PopOS (based on ubuntu)
- Clio: 0.10.0
- Node: v16.9.1
- NPM: 7.21.1

**Possible solutions**
- Fix imports (?)

**Additional context**
i get 
```
Cannot find module "express" in your project.
Are you sure it is installed?
```

**Comment by pouya-eghbali** [comment]
Hi, thanks for reporting the issue. In the newer versions, JavaScript imports should be prefixed with `js:`, for example:

```clio
import "js:express"
```

This wasn't reflected in the documentation, will be in the docs when #227 is merged.

You can also check out the `express` example in the examples repo: https://github.com/clio-lang/examples/blob/master/express/src/main.clio
