### ISSUE TITLE
The new Clio

### ISSUE THREAD

**Issue by pouya-eghbali** [clio-lang/clio#24]
I'm working on a new Clio, the syntax and the features will be (almost) the same, but the way the language works will be different. There are several reasons for this:

- A better parser, with better error reporting
- Cleaner CST / AST
- Cleaner code generation
- No more custom types in core, we'll compile to vanilla JS
- No more custom scopes, custom functions, etc

Here are the required steps and the current state:

- [X] Write a new lexer
- [X] Write a new parser
- [X] Make a new AST format
- [X] Make a new code generator
- [ ] Make a core library to provide functional programming / lazy evaluation tools

You can check the code of the new parser here: https://github.com/pouya-eghbali/bean
I'll move this repository to Clio organization when all above steps are finished.

**Comment by pouya-eghbali** [comment]
The new code generator is in the bean repo. It doesn't make a meaningful JavaScript, but it works. Feel free to check, modify or make requests. Once finished we'll be able to write a decent standard library for Clio.

**Comment by pouya-eghbali** [comment]
The code generator works, however in order to generate code that makes sense we need to have a stdlib first. I'm working on this.

**Comment by garritfra** [comment]
What are you putting in the stdlib?

**Comment by pouya-eghbali** [comment]
> What are you putting in the stdlib?

We'll start by some lazy data types, some functional programming utilities, and some scientific data types (like decimal for example). Then we'll do Clio Enhancement Proposals to see what we should do next!

**Comment by garritfra** [comment]
Will try to integrate parser to main repo today. We can continue working on it from there

**Comment by pouya-eghbali** [comment]
We'll have another official generator later, but let's not worry about that now. Later we'll move the js generator to a ./targets/javascript`

**Comment by garritfra** [comment]
Not relevant anymore. Has been split up into multiple issues. See https://github.com/orgs/clio-lang/projects/1
