### ISSUE TITLE
Common FP operations

### ISSUE THREAD

**Issue by fuzzthink** [clio-lang/clio#25]
How to do:
mapi, fold/reduce, map2, partition?

**Comment by raphaelkieling** [comment]
it's a good question. i not found in [doc](https://docs.clio-lang.org)

**Comment by garritfra** [comment]
These methods are not implemented in clio. As of now, you can simply ES6 higher order functions. If you want to use more advanced FP techniques, I recommend you check out the [Ramda](https://ramdajs.com/) or [Lodash](https://lodash.com/) library. 
I really like the idea of natively supporting FP functions. @pouya-eghbali should this be on our roadmap?

**Comment by garritfra** [comment]
Whoops, I've overlooked that is already is on the roadmap! Closing this for now
