### ISSUE TITLE
Clio introduction requires paid subscription :-(

### ISSUE THREAD

**Issue by jkleiser** [clio-lang/clio#27]
The intro at https://blog.usejournal.com/introduction-to-clio-40dbbf9c250b requires a paid Medium subscription. I would rather pay for Clio, if it's any good.

**Comment by jkleiser** [comment]
I notice that if I go to the intro article from this page https://docs.clio-lang.org/medium-articles, then I may read it freely. :-)

**Comment by pouya-eghbali** [comment]
Hello @jkleiser , I just made the posts free.

https://blog.usejournal.com/introduction-to-clio-40dbbf9c250b
https://medium.com/@eghbali/making-a-reactive-to-do-app-with-clio-ac7bf8b93959

These posts are a little outdated, I don't have much free time to work on Clio anymore. But soon I'll be able to start working on it again.
