### ISSUE TITLE
How can i do the parallel programming in Clio ?

### ISSUE THREAD

**Issue by R2D2-fwks** [clio-lang/clio#29]
Hi, 

I am curious about the parallel programming in Clio. As I was going through the code (not in-depth ) as it is more kind of a wrapper over js. being js works on single thread. Have you included the thread concept through Native support of C++ lib of Nodejs . It will be pretty interesting to see.

**Comment by garritfra** [comment]
Hi, thanks for your suggestion! We will focus on this topic in the future. Right now, we're still stabilizing the language. If you want to, you can join our [telegram group](https://t.me/joinchat/B0kZo0kVldfXldTDqz95XA) to keep updated on this topic! :)
