### ISSUE TITLE
Use FS module to generate a new project

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#40]
We're currently using the `shelljs` library to generate a project via `clio new`. That breaks platform compatibility, as the shell syntax for UNIX and windows are quite different.

- [ ] Rewrite CLI commands to use FS instead of shelljs
- [ ] Rewrite tests to use functions provided by the cli instead of calling Clio commands via shell
- [ ] Review usage of file paths in CLI functions. Should accept absolute paths to simplify tests

**Comment by andreyluiz** [comment]
@garritfra Please, assign this one to me. :)
