### ISSUE TITLE
Host in docker container

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#41]
Clio modules should be able to be hosted in a Docker container. A directory containing the project including the clio.toml file can be passed in. The project is hosted via `clio host`

### EDIT after telegram discussion

We have agreed that hosting will either be possible through a built-in process manager (separate issue will be created), or via a docker container. The user should be able to write a Dockerfile that builds on top of the official Clio Dockerfile to host their files.
```Dockerfile
FROM clio-lang/clio:latest
COPY . .
EXPOSE 3000
CMD ["clio", "host", "index.clio"]
```

**Comment by pouya-eghbali** [comment]
I'd like to move host configuration to a host.toml or just into cliopkg.toml. Previously host utility needed the scripts to _export_ a host configuration.

**Comment by garritfra** [comment]
You mean a js wrapper?

**Comment by pouya-eghbali** [comment]
> You mean a js wrapper?

I mean, we needed to do:

```clio
{
  #port 3000
  #workers 8
  #exports [
    #alpha
    #beta
  ]
} => host
```

in a Clio file in order to host it. But it would be better if we can do that in project config file like this:

```toml
[host]
port = 3000
workers = 8
exports = ["alpha", "beta"]
```

**Comment by garritfra** [comment]
We could make the port and workers optional fields. If no value is provided, we could assign a default port and number of workers. In rust, you specify the modules you want to export in a top level `lib.rs` file. What do you think about this?

**Comment by garritfra** [comment]
Should we note this feature somewhere and close this issue?

**Comment by garritfra** [comment]
Closed. Not yet relevant

**Comment by pouya-eghbali** [comment]
I guess this is very, outdated.

**Comment by garritfra** [comment]
It's something we could tackle at some point, but right now it's not relevant
