### ISSUE TITLE
Add default .gitignore file when creating a new project

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#42]
`clio_env` and `.clio-cache` are in the working tree when a new project is created. That should not be the case.

**Comment by pouya-eghbali** [comment]
It's funny how one uses `_` and the other `-`

**Comment by andreyluiz** [comment]
@garritfra, which version?
On `develop` a `node cli new test-project` yields this, for me:
<img width="164" alt="Screenshot 2019-12-17 at 15 31 02" src="https://user-images.githubusercontent.com/1965897/71009508-41642000-20e2-11ea-8fe1-42bbb9c89d94.png">

**Comment by garritfra** [comment]
@andreyluiz is your working tree clean?

**Comment by andreyluiz** [comment]
Yup. Freshly cloned. I ran it again and still it yield the same as the print screen above.

**Comment by garritfra** [comment]
```
▶ git status 
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	clio_env/

nothing added to commit but untracked files present (use "git add" to track)
```

clio_env is subject to change. Think of it as the `node_modules` for clio. It should not be commited

**Comment by garritfra** [comment]
Thats weird. Just tested it with 0.1.6. Let me check develop

**Comment by andreyluiz** [comment]
Oh, I see what's wrong. I didn't `cd` into the project to make a git status. Now I see it untracked. You're right. My bad.

**Comment by garritfra** [comment]
Do you want to take on this issue?

**Comment by andreyluiz** [comment]
Yup, please.
