### ISSUE TITLE
Add supported engines on package descriptor

### ISSUE THREAD

**Issue by andreyluiz** [clio-lang/clio#46]
I suggest we add to the `package.json` file the field engines to instruct who will use or collaborate with the project which version of Node and/or NPM to use. For example:

```json
"engines": {
  "node": ">=10.0",
  "npm": ">=3"
},
```

Optionally, we can also add a `.nvmrc` on the root of the project, so who uses NVM could just do an `nvm use` on the root of the project to know which version to install with the NVM. This, though is really optional since it relies on an external tool which maybe few people use (I use it).

**Comment by garritfra** [comment]
@pouya-eghbali What do you think?
I'd suggest node version >=10.4, because as of now we are using BigInts

**Comment by garritfra** [comment]
TODO: 
- [ ] Check if Warning appears when installed globally

**Comment by garritfra** [comment]
Warning does not appear when installed via `npm link`.
I'll add a warning for the user
