### ISSUE TITLE
Pre-commits dont run on free-bsd

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#48]
**Describe the bug**

Pre-commit hooks do not run on free-bsd because `#!/bin/bash` is not available. https://github.com/observing/pre-commit could be forked to use a more generic `#!` like `/usr/bin/env bash` and then published as a new package. Another (probably simpler solution) would be to replace the `pre-commit` dep with a different one entirely

Things to check:
- [x] Is `/usr/bin/env` always given on most operating systems?

**To Reproduce**
1. Run `npm i`
1. Make changes
2. Commit

**Expected behavior**
Pre-commits run smoothly

**Versions (please complete the following information):**
 - OS: free-bsd
 - Clio: 0.1.6
 - Node: latest
 - NPM: latest

**Additional context**
https://github.com/observing/pre-commit

**Comment by pouya-eghbali** [comment]
It's not only freebsd, I think `/bin/bash` is linux only (maybe mac too?), but that's not the case on BSDs or other *nix operating systems. Not sure about Haiku and others.

If node runs on these operating systems this should also run them. Not sure if there's a way to generate the pre-commits file depending on the os, but I think finding a portable solution is best.

**Comment by garritfra** [comment]
@pouya-eghbali should we remove the precommit hook entirely? The lint checker is also running in CI, which should catch all style issues

**Comment by garritfra** [comment]
Closed by 6843e9c7857ffe08adf7b27b9c0168b65df928f1
