### ISSUE TITLE
Change how the compilation works

### ISSUE THREAD

**Issue by pouya-eghbali** [clio-lang/clio#50]
For compilation, I did what Python does when I first wrote Clio. Python compiles the files on import and caches them in a `__pycache__` directory. I did the same and this caused a lot of issues with imports.

Node doesn't know about our cache directory or our compile on import strategy, so on every import I had to check:

1. is this a js import?
  1.1. import js from `..` (we're in cache dir)
2. is it a clio import?
  2.1. resolve import path from `..`
  2.2. compile if it's not compiled
  2.3. import from `../path/to/file/cache/file`
3. is it an unknown import?
  3.1. assume clio import 
  3.1. if import fails, assume js

If the above fails, we had to check places outside the project directory, for example globally installed clio modules (if such thing exists)

I also wrote a require function for the browser. It was possible to just do:

```html
<script type="text/clio">
"Hello world" -> print
</script>
```

Or
```html
<script type="text/clio" src="index.clio"></script>
```
 And even this was possible:
```html
<script type="text/clio">
import something from somewhere
data -> something 
</script>
```

We used to compile on the browser, calculate a hash for each file, and cache the compile results on the browser. 

I suggest we don't do any of these anymore. For node, we'll compile all files in the project directory and put them in a `.clio/cache/node`, this solves the issues with imports, it simplifies dependency management, and a lot of other things. 

For the browser, I suggest we do something similar and then generate a bundle from the compiled files.

**Comment by garritfra** [comment]
In other languages like rust and swift, the compiled files go to `target/debug/compiledfile`.
We could do a similar approach, like `target/node/debug`, later also `target/node/release` and even later `target/browser/release`. Cached files could live in `target/browser/.cache`. What do you think?

**Comment by andreyluiz** [comment]
`.clio` would be the replacement of the `clio_env`?

**Comment by pouya-eghbali** [comment]
Yes. We'll replace .clio_env with .clio, and we get rid of .clio-cache

**Comment by garritfra** [comment]
Currently we're using `clio_env`. It's a visible directory. Should it still be visible or hidden?

**Comment by pouya-eghbali** [comment]
I'd say hidden. Hidden makes more sense to me. User can pass a different path to the compiler if they want to see the generated code.

**Comment by pouya-eghbali** [comment]
Closing this. Not relevant anymore. We should get rid of `clio_env` and `.clio`, they're not needed.
