### ISSUE TITLE
Prettify CLI messages

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#52]
I noticed that some CLI commands crash with an ugly error message when an incorrect filepath is provided. These crashes should be catched, handled and displayed as a human-friendly message:

- [x] `clio run`
- [x] `clio new`
- [x] `clio ast`
- [x] `clio highlight`
- [x] `clio compile`

EDIT: @andreyluiz noted, that the CLI could need some color in general. This will be part of this issue

**Comment by garritfra** [comment]
What about some emojis?✨

**Comment by andreyluiz** [comment]
Yes, I think we can use some emojis. :)

**Comment by garritfra** [comment]
I also noticed, that this "cliopkg.toml is missing, or are you running tests" message is performed way too often. I think that has something to do with the way I have implemented it: 
```js
(x => do(x))()
```
Could you also take care of that?

**Comment by andreyluiz** [comment]
Yup, no problem. I'll try to reduce its frequency.
