### ISSUE TITLE
Improve new command project structure

### ISSUE THREAD

**Issue by andreyluiz** [clio-lang/clio#64]
**Is your feature request related to a problem? Please describe.**
When a new project is created, it is not clear how to target it for the browser. There is no script for Clio language available on the generated project, also there are no instructions on how to do it.

**Describe the solution you'd like**
I would like to have a flag on the new command like `--browser` where I specify that this project is intended to run on the browser. If this file is declared, then the project should be generated with everything set up to start hacking with Clio on the browser.

**Describe alternatives you've considered**
I considered using https://github.com/Rich-Harris/degit to accomplish that. We would have two or three sample repositories with ready-to-start structures and using degit, we simply create the projects using the repositories as a base. Degit is pretty modular and language agnostic. It has an API and inits a new git repository, instead of a simple `git clone`. 

**Additional context**
Clio new command should make the required directories (src, build, docs...).

**Comment by garritfra** [comment]
`--target=<targetname>` could also be possible. That loads `<targetname>-generator.js` from a directory. If no generator was found, we'll throw an error

**Comment by andreyluiz** [comment]
Is it necessary to throw an error? Can't we just assume a default?

**Comment by garritfra** [comment]
If no target is given, we will assume a default. But when a generator is passed that does not exist, we could throw an error. What do you think?

**Comment by andreyluiz** [comment]
Closed by #83.
