### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by pouya-eghbali** [clio-lang/clio#65]
Currently only `if elif else` is defined, other forms (for example `if else`) aren't defined and they do not work. Currently we have 1 parser rule for each combination (`if_elif_conditional`, `if_else_conditional`, ...), we should probably rename all of them to just `conditional`.

- [x] Fix parsing rules (Rename to `conditional` and make the rule a valid entry in `block`s)
- [x] Replace `if_elif_else_conditional` in generator with `conditional` and make necessary modifications

**Comment by garritfra** [comment]
Are we going to use `elif` or `else if`?

**Comment by pouya-eghbali** [comment]
I tried to do `else if` but it didn't look consistent with the rest of the syntax, so I reverted to `elif`
