### ISSUE TITLE
Doublequoted strings 

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#7]
I've been used to using doublequotes for strings, however they are not usable in clio yet. What do you think about implementing it? Are there any downsides?

**Comment by garritfra** [comment]
d4bddb9 adds support for doublequotes, however i see a problem in the usage, as `"My String'` would be a valid string.

**Comment by pouya-eghbali** [comment]
We can probably use regex backreferences, 

```
/^(['"])([^\\]|\\.)*?\1/
```

not sure which approach is better, I should check if we're using regex groups to get the match in the lexer
