### ISSUE TITLE
Make Clio available on CDN.js

### ISSUE THREAD

**Issue by andreyluiz** [clio-lang/clio#75]
**Is your feature request related to a problem? Please describe.**
We don't have a way of importing Clio from a CDN. This is a very common practice on the front-end world.

**Describe the solution you'd like**
We need to host Clio on a CDN provider.

**Describe alternatives you've considered**
CDN.js is a good choice. It is free and widely used by the community.

**Additional context**
We need to open a PR on https://github.com/cdnjs/cdnjs to make it available. This issue will be used to track the progress.

**Comment by garritfra** [comment]
Closed, as discussed on telegram
