### ISSUE TITLE
Define strategy to bundle browser files

### ISSUE THREAD

**Issue by andreyluiz** [clio-lang/clio#82]
**Is your feature request related to a problem? Please describe.**
Following up on #64, we should define a strategy to make the built JavaScript file from Clio source ready to run in the browser.

**Describe the solution you'd like**
`clio build` script should do some steps:
1 - Compile the Clio source into JS code (this is being done already);
2 - Install dependencies on the bundle directory (there will be a package.json there);
3 - Call an NPM script (declared in the package.json) to bundle the JavaScript files;

`clio build` should take a flag `--no-bundle` that should avoid step three from happening.

Just like `clio build`, `clio run` should cover all the 3 steps describe above, and execute the 4th step to make the compiled source available through a static HTTP server.

**Describe alternatives you've considered**
Inside the build directory (conventioned as `build/browser`), we should have a package.json with two scripts to bundle and host. We are considering using *parcel* to bundle because it is a zero-configuration bundler. For the HTTP I suggest `http-server`.

**Additional context**

**Comment by mindrones** [comment]
I've been trying to compile `browser.js` with `rollup` and I noticed that there are dependencies thst seem related to the online editor (chalk for example) [1].

This made me think that probably we don't want to have that code in the bundle we use in a web app, so probably it would make sense to have a `clio.editor.js` for the website and the playground and a `clio.js` with internals only, also as Gavin mentioned to reduce the size of the production bundle.

[1]
<img width="508" alt="Screenshot 2020-01-02 at 11 35 57" src="https://user-images.githubusercontent.com/1309648/71669874-14f90680-2d66-11ea-845e-232371debef5.png">
