### ISSUE TITLE
Auto generate package.json on build directory

### ISSUE THREAD

**Issue by andreyluiz** [clio-lang/clio#90]
This issue follows #64 and #87.

**Is your feature request related to a problem? Please describe.**
Our current template projects https://github.com/clio-lang/template-node and https://github.com/clio-lang/template-browser have a static `package.json` inside `build/<target>`. In the case of `browser` target, it also has an `index.html` If the programmer resolves to change the build directory, the `package.json` file has to be moved. And this is not ideal.

**Describe the solution you'd like**
When running `clio build`, the `package.json` and `index.html` (in `browser` targets) should be automagically generated inside wherever the bundle directory is.

**Describe alternatives you've considered**
We could use an NPM init to do that, or just create a file from a string. For `browser` target, `index.html` should be created too.

**Additional context**
The NPM scripts on the `package.json`.

1) `build` script should be `parcel build index.html --out-dir public`;
2) Add a `run` script with `parcel index.html --out-dir public`;

`build` for `clio build` and `run` for `clio run`. :ok_hand:

Also, we need to create a `.gitignore` too. I think we can use https://raw.githubusercontent.com/github/gitignore/master/Node.gitignore.

**Comment by garritfra** [comment]
Closed by #93
