### ISSUE TITLE
IO instance is printed to stdout

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#96]
**Describe the bug**
An instance of IO is printed to stdout when running a compiled program. I can't exactly point out where it is printed yet.

**To Reproduce**
1. Create project using `clio new`
2. Compile the following program using the `v0.2.0` dev version:
```
fn fib n: 
  if n < 2:
    "smaller than 2" -> print
  else:
    "larger or equal 2" -> print

2 -> fib -> print

```

3. Run `node build/node/src/main.clio.js` to execute the binary

**Expected behavior**
Just "larger or equal 2" should be printed.

**Screenshots**
<img width="445" alt="Bildschirmfoto 2020-01-02 um 19 54 16" src="https://user-images.githubusercontent.com/32395585/71685813-ab92eb00-2d99-11ea-86fa-291700c0579f.png">

**Versions (please complete the following information):**
 - OS: macOS Catalina
 - Clio: v0.2.0 (dev)
 - Node: v12.13.1
 - NPM: 6.13.4
 
**Possible solutions**
 - Probably just a random console.log somewhere

**Comment by pouya-eghbali** [comment]
This is now fixed in develop.

**Comment by pouya-eghbali** [comment]
Closing this
